--- 
- include_tasks: configure_angular.yml
  tags: [ install, update ]

- include_tasks: run_angular.yml
  tags: [ install, update ]

- include_tasks: configure_node.yml
  tags: [ install, update ]

- include_tasks: run_node.yml
  tags: [ install, update ]

- include_tasks: link_logs.yml
  tags: [ install, update ]
