---
- name: Installing curl
  apt: name=curl

- name: Downloading Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.19.2/prometheus-2.19.2.linux-amd64.tar.gz
    dest: /tmp

- name: Extract prometheus 
  unarchive:
    src: "/tmp/prometheus-2.19.2.linux-amd64.tar.gz"
    dest: "{{ base_dir }}/cqube/admin_dashboard/"

- name: Rename the extracted folder
  shell: mv {{ base_dir }}/cqube/admin_dashboard/prometheus* {{ base_dir }}/cqube/admin_dashboard/prometheus

- name: Configuring the prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: "{{ base_dir }}/cqube/admin_dashboard/prometheus/prometheus.yml"

- name: Executing the Prometheus
  shell: nohup ./prometheus --config.file=prometheus.yml &
  args:
    chdir: "{{ base_dir }}/cqube/admin_dashboard/prometheus/"

- name: Downloading node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /tmp

- name: Extract node_exporter 
  unarchive:
    src: "/tmp/node_exporter-1.0.1.linux-amd64.tar.gz"
    dest: "{{ base_dir }}/cqube/admin_dashboard/"

- name: Rename the extracted folder
  shell: mv {{ base_dir }}/cqube/admin_dashboard/node_exporter* {{ base_dir }}/cqube/admin_dashboard/node_exporter

- name: Executing the Prometheus
  shell: nohup ./node_exporter &
  args:
    chdir: "{{ base_dir }}/cqube/admin_dashboard/node_exporter/"

