---
nifi_crc: true
nifi_attendance: true
nifi_semester: true
nifi_infra: true
nifi_diksha: true
nifi_telemetry: true
nifi_udise: true
nifi_pat: true
nifi_composite: true
nifi_healthcard: true
nifi_teacher_attendance: true
nifi_data_replay: true
nifi_sat: true