---
- name: Installing cQube
  hosts: localhost
  remote_user: root
  vars_files:
    - config.yml

  roles:
          - create_base_dir
          - java
          - python
          - createdb
          - python_flask
          - keycloak
          - grafana
          - angular
          - angular_admin
          - nifi_params
          - nifi_install
          - nifi_crc
          - nifi_static
          - nifi_attendance
          - nifi_semester
          - nifi_infra
          - nifi_diksha
