---
- name: Upgrading cQube
  hosts: localhost
  gather_facts: true
  remote_user: root
  vars_files:
    - upgradation_config.yml  
    - datasource_config.yml
    - memory_config.yml
    - .version
    
  roles: 
          - datasource
          - createdb
          - python_flask
          - { role: kong, tags: update }
          - keycloak
          - angular
          - angular_admin
          - prometheus
          - nifi_install
          - { role: nifi_params, tags: update } 

          - role: nifi_crc
            tags: update
            when: nifi_crc

          - role: nifi_static
            tags: update

          - role: nifi_attendance
            tags: update
            when: nifi_attendance

          - role: nifi_semester
            tags: update
            when: nifi_semester

          - role: nifi_infra
            tags: update
            when: nifi_infra

          - role: nifi_diksha
            tags: update
            when: nifi_diksha

          - role: nifi_telemetry
            tags: update
            when: nifi_telemetry

          - role: nifi_udise
            tags: update
            when: nifi_udise

          - role: nifi_pat
            tags: update
            when: nifi_pat

          - role: nifi_composite
            tags: update
            when: nifi_composite

          - cqube_version
