---

# Defaults: 

sftp_group: cqubegroup
sftp_dir: cqube
db_user: 
db_name: 
db_password:                            # md5 password

nifi_port: 8096
nodejs_version: "12"
ansible_distribution_release: trusty
api_endpoint:                         #https://domain.com/api


s3_input_bucket: cqube-input
s3_output_bucket: cqube-output
sftp_hostname: localhost
sftp_input: /cqube/data/emits
sftp_port: 22
sftp_user: cqube        # Enter the sftp user needs to be created
sftp_key_path: /home/cqube/.ssh/id_rsa          # ex: /home/<sftp_user_name>/.ssh/id_rsa
sftp_school_master: /cqube/data/school_master
sftp_lat_long: /cqube/data/lat_long
s3_school_master_lat_long: /cqube/data/s3_school_latlong
postgre_driver_class_name: org.postgresql.Driver
postgre_connection_url: jdbc:postgresql://localhost:5432/
postgre_source_db: cqubedev
postgre_dtn_db: cqubedev
postgre_db_user: postgres
postgre_pwd: psql
sftp_school_hierarchy: /cqube/data/school_hierarchy
sftp_roles_master: /cqube/data/roles_master
sftp_users_master: /cqube/data/users_master
sftp_error_dir: /cqube/data/errors
sftp_student_sem: /cqube/data/student_sem
sftp_crc_input: /cqube/data/crc_input

# Needs to filled manually:

s3_access_key:       # AWS Access key
s3_secret_key:      # AWS Secret key
postgre_driver_dir: jars/postgresql-42.2.10.jar       # ex: /<path_of_cloned_directory/cQube/development/nifi/jars/postgresql-42.2.10.jar







