---
- name: Creating the server_side Directory for the installation
  file: 
    path: "{{ base_dir }}/cqube/dashboard/server_side"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    recurse: yes
    state: directory
    
- name: copying server-side script
  shell: "cp -R ../../development/angular/server-side {{base_dir}}/cqube/dashboard/server_side"

- name: Change to Node directory
  shell: "cd {{base_dir}}/cqube/dashboard/server_side"

- name: NodeJS dependencies install
  npm:
    path: "{{base_dir}}/cqube/dashboard/server_side"

- name: Creating environmental variables
  file:
    path: "{{base_dir}}/cqube/dashboard/server_side/.env"
    state: touch
    mode: u+rw,g+rw,o+rw

- name: Loading required data inside .env file
  blockinfile:
    path: "{{base_dir}}/cqube/dashboard/server_side/.env"
    block: |
      PORT = 3000
      ACCESS_KEY_ID = "{{ s3_access_key }}"
      SECRET_ACCESS_KEY  = "{{ s3_secret_key }}"
      OUTPUT_BUCKET = "{{ s3_output_bucket }}"
