---
- name: checking process of pm2 client_side
  become: yes
  shell: pm2 id client_side
  register: pm2_output
  tags: install

- name: checking the existing pm2 processes if running
  shell: pm2 delete client_side
  when: pm2_output.stdout != "[]"
  ignore_errors: True
  become: yes
  tags: install

- name: Starting the http-server
  become: yes
  shell: pm2 start /usr/bin/http-server --name client_side -- -a {{ local_ipv4_address }} -p 4200 
  args:
    chdir: "{{ base_dir }}/cqube/dashboard/client_side/dist/client-side"
  tags: install

- name: Starting the client_side app
  become: yes
  shell: pm2 start client_side
  tags: update

