- name: Installing python3
  apt: name=python3
- name: Installing pip
  apt: name=python3-pip
- name: Installing pip3
  apt: name=python-pip
- pip:
    name: boto3
 
- name: Install required packages
  apt:
    pkg:
    - python3-dev
    - build-essential
    - libssl-dev
    - libffi-dev
    - virtualenv
    - python3-setuptools 
