--- 
keycloak_version: 10.0.2
keycloak_dir: "{{ base_dir }}/cqube"
keycloak_archive: keycloak-{{ keycloak_version }}.tar.gz
keycloak_url: https://downloads.jboss.org/keycloak/{{ keycloak_version }}/{{keycloak_archive }}

keycloak_jboss_home: "{{ keycloak_dir }}/keycloak"
keycloak_log_dir: "{{ keycloak_jboss_home }}/standalone/log"

realm_name: cQube
realm_created: False
cQube_realm_json: "{{ base_dir }}/cqube/keycloak/kc_templates/cQube_realm.json"

